name: enekeskonyv
description: Református énekeskönyv (21-es kék és 48-as fekete)

publish_to: 'none'

version: 2.2.2+10

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  wakelock: ^0.6.1+1
  provider: ^6.0.4
  shared_preferences: ^2.0.15

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon-play_store.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/enekeskonyv.json
    - assets/ref48/
    - assets/ref21/
