name: enekeskonyv
description: Református Énekeskönyv (21/48)

publish_to: 'none'

version: 3.1.0+47

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.4
  wakelock_plus: ^1.1.0
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.14
  mailto: ^2.0.0
  fading_edge_scrollview: ^4.1.1
  diacritic: ^0.1.4
  app_links: ^4.0.0
  qr_flutter: ^4.1.0
  share_plus: ^7.0.0
  package_info_plus: ^5.0.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon-play_store.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/enekeskonyv.json
    - assets/ref48/
    - assets/ref21/
